export const productNames = [
    "Creek Classic CD",
    "Creek Destiny CD",
    "Creek Evo CD",
    "Exposure 2010S CD",
    "Creek Classic",
    "Exposure 2010S",
    "Parasound D200",
    "Parasound Halo D3",
    "Manley Mahi",
    "Manley Neo-Classic 300B",
    "Manley Snapper",
    "Parasound Halo A23",
    "Creek OBH-22 Passive Preamp",
    "Parasound Classic 7100",
    "Parasound Halo P3",
    "Project Pre Box",
    "Bösendorfer VCS Wall",
    "Epos M5",
    "Harbeth HL7ES2",
    "Harbeth Monitor 30",
    "Harbeth P3ES2",
    "Creek A50I",
    "Creek Classic 5350SE",
    "Creek Destiny Amp",
    "Manley Snapper",
    "Manley Stingray",
    "Pro-Ject Debut III",
    "Pro-Ject RPM 5",
    "Pro-Ject RPM 10"
];